# Generated by Django 2.1.5 on 2019-11-19 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191119_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water',
            name='water_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 19, 14, 45, 52, 348669), verbose_name='Date and Time'),
        ),
        migrations.AlterField(
            model_name='water',
            name='water_title',
            field=models.CharField(default='Upcoming Watering', max_length=200),
        ),
    ]
